# Generated by Django 3.2.13 on 2023-05-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0002_savingoptions_savingproduct'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='asset_holdings',
            field=models.CharField(blank=True, choices=[('1천만원 이하', '1천만원 이하'), ('3천만원 이하', '3천만원 이하'), ('1억원 이하', '1억원 이하')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='financial_goal',
            field=models.CharField(blank=True, choices=[('브론즈', '브론즈'), ('실버', '실버'), ('골드', '골드'), ('플래', '플래'), ('다이아', '다이아')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='investment_experience',
            field=models.CharField(blank=True, choices=[('적다', '적다'), ('중간', '중간'), ('많다', '많다')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, choices=[('학생', '학생'), ('직장인', '직장인'), ('전업주부', '전업주부'), ('취준생', '취준생')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='monthly_expenses',
            field=models.CharField(blank=True, choices=[('오십만원 이하', '오십만원 이하'), ('백만원 이하', '백만원 이하'), ('삼백만원 이하', '삼백만원 이하'), ('오백만원 이하', '오백만원 이하'), ('천만원 이하', '천만원 이하')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_bank',
            field=models.CharField(blank=True, choices=[('국민은행', '국민은행'), ('기업은행', '기업은행'), ('신한은행', '신한은행'), ('KEB하나은행', 'KEB하나은행'), ('우리은행', '우리은행'), ('하나은행', '하나은행'), ('외환은행', '외환은행'), ('SC제일은행', 'SC제일은행')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='saving_preference',
            field=models.CharField(blank=True, choices=[('예금', '예금'), ('적금', '저금'), ('대출', '대출'), ('기타', '기타')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribed_products',
            field=models.ManyToManyField(blank=True, null=True, to='finlife.DepositProduct'),
        ),
    ]
